import type { CodePrompt } from '../types';

export const CODE_PROMPTS: CodePrompt[] = [
  {
    id: '17',
    title: '交互式 Canvas 风铃',
    model: 'GPT-4',
    promptZh: '请写一个 React 组件，使用 HTML5 Canvas 实现一个日式风铃的效果。要求：\n1. 风铃随鼠标移动产生的微风摆动。\n2. 有清脆的铃声效果（可选）。\n3. 视觉风格清新，带有夏季氛围。',
    promptEn: 'Create a React component that uses HTML5 Canvas to implement a Japanese wind chime effect. Requirements:\n1. The wind chime swings with the breeze generated by mouse movement.\n2. Crisp chime sound effect (optional).\n3. Fresh visual style with a summer atmosphere.',
    description: '一个基于 HTML5 Canvas 的日式风铃交互组件，适合前端开发展示。',
    category: '代码开发',
    source: '原创',
  },
];
